### ISSUE TITLE
Fade in/out shape property can never be set to 0 once changed

### ISSUE THREAD

**Issue by eobet** [Eneskp3441/Shaker#3]
If you ever change the default fade in/out values, they can never be set to 0 again:

![image](https://github.com/user-attachments/assets/e8da6641-7a8a-404e-b396-8f576ff79651)

It may say zero, but you can see on the graph that it is not and if you click the value, you'll see that it's in fact a really, really tiny decimal number.

**Comment by Eneskp3441** [comment]
Hi! I'm using @export_exp_easing and I couldn't find a way to make it equal to 0, but I fixed the way it processes and appears in the graph, so that if it's very close to 0, it will detect it as 0.

but if the reset button appears, you can reset the value to 0 here.
![image](https://github.com/user-attachments/assets/bc896a24-4451-4b69-8850-cd5e11612759)
